config/routes.rb
Rails.application.routes.draw do
  resources :movies, only: %i[index show]
  resources :lists, only: %i[index show new create delete destroy] do
    resources :bookmarks, only: %i[create new]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)

    # we need `list_id` to associate bookmark with corresponding list
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    # we need `list_id` to delete bookmark (look in app/views/bookmarks/_bookmark.html.erb)
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.where(list_id: @list.id)
    @movies_in_list = @bookmarks.map { |bookmark| bookmark.movie }
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= link_to "< back", list_path(@list), class: "back-button"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="header">
  <h1>My Lists</h1>
</div>
<%= link_to "+ new list", new_list_path, class: "admin-button"%>
<%= link_to "< back", movies_path, class: "back-button"%>
<div class="grid">
  <% @lists.each do |list| %>
    <div class="card-list">
      <div class=card-list-images-container>
        <div class="card-list-images-grid">
          <% bookmarks = Bookmark.where(list_id: list.id) %>
          <% movies_in_list = bookmarks.map { |bookmark| bookmark.movie } %>
          <% movies_in_list.each do |movie| %>
            <img src="https://image.tmdb.org/t/p/w300<%= movie.poster_url %>">
          <% end %>
        </div>
      </div>
      <div class="card-list-infos">
        <h2><%= link_to list.name, list_path(list), class: "card-list-name" %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= link_to "< back", lists_path, class: "back-button"%>
<h1>New list</h1>
<div class="container-form">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<%= link_to "< back", lists_path, class: "back-button"%>
<h1><%= @list.name %></h1>
<%= link_to "delete list", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "admin-button"%>
<%= link_to "+ new bookmark", new_list_bookmark_path(@list), class: "admin-button-two"%>
<div class="grid-dark">
  <% @movies_in_list.each do |movie| %>
    <div class="card-movie">
      <img src="https://image.tmdb.org/t/p/w400/<%= movie.poster_url %>"/>
      <div class="card-movie-infos">
        <h2><%= link_to movie.title, movie_path(movie), class: "card-movie-name" %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%= link_to "MY LISTS", lists_path, class: "admin-button"%>
<div class="grid">
  <% @movies.each do |movie| %>
    <div class="card-movie">
      <img src="https://image.tmdb.org/t/p/w400/<%= movie.poster_url %>"/>
      <div class="card-movie-infos">
        <h2><%= link_to movie.title, movie_path(movie), class: "card-movie-name" %></h2>
        <p><%= movie.rating %> <%= icon('far', 'star')%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<%= link_to "< back", movies_path, class: "back-button"%>
<div class="container-movie">
  <img src="https://image.tmdb.org/t/p/w400/<%= @movie.poster_url %>"/>
  <div class="container-movie-info text-center p-4">
    <h1><%= @movie.title %></h1>
    <p class="movie-rating"><%= @movie.rating %> <%= icon('far', 'star')%></p>
    <p><%= @movie.overview %></p>
    <%= link_to "add to list", lists_path, class: "button" %>
  </div>
</div>